name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: cachix/install-nix-action@v10
    - run: nix-shell --run 'npm install'
    - run: nix-shell --run 'node_modules/.bin/shadow-cljs compile :test'
    - run: nix-shell --run 'node out/tests.js'
    - run: nix-shell --run 'node_modules/.bin/shadow-cljs release :cli'
    - run: nix-shell --run 'node out/replant test/Apple.kt'
    - run: cat out/apple.ts
