name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: cachix/install-nix-action@v10
    - run: nix-shell --run 'npm i && node_modules/.bin/shadow-cljs compile :test && node out/tests.js'
